//! A human-friendly 7 characters identifier format (e.g. `123abcd`).
//!
//! For a language agnostic specification of the caretta-id format, see [SPECS.md](https://github.com/fluo10/caretta-id/blob/main/SPECS.md)
//!
//! # Quick Start
//!
//! ```
//! use caretta_id::CarettaId;
//!
//! let id = CarettaId::random();
//! println!("{}", id); // e.g. "123abcd"
//! ```
//!
//! # Why caretta-id?
//!
//! Traditional identifier systems face challenges in distributed environments:
//!
//! - **Sequential numbers** (like GitHub issue numbers) cause collisions in distributed systems
//! - **UUIDs** are too long and not human-friendly
//! - **Short hashes** (like Git commit hashes) lack standardization
//!
//! caretta-id bridges the gap between human readability and technical requirements.
//!
//! # Installation
//!
//! Add this to your `Cargo.toml`:
//!
//! ```toml
//! [dependencies]
//! caretta-id = "1.0"
//!
//! # With optional features
//! caretta-id = { version = "1.0", features = ["arbitrary", "serde", "rusqlite", "sea-orm", "prost", "redb"] }
//! ```
//!
//! ## For no_std Environments
//!
//! This crate support `no_std`.
//! For `no_std` environment, you'll need to disable default features.
//!
//! ```toml
//! [dependencies]
//! caretta-id = { version = "1.0", default-features = false }
//! ```
//!
//! # Features
//!
//! - **Human-friendly**: Easy to read, type, and communicate
//! - **Collision-resistant**: Sufficient entropy for personal distributed systems
//! - **Compact**: Shorter than UUIDs while maintaining uniqueness
//! - **Type-safe**: Rust implementation with strong typing
//! - **Multiple integrations**: Support for serde, rusqlite, sea-orm, and protobuf
//!
//! ## Optional Feature Flags
//!
//! - `arbitrary`: `arbitrary::Arbitrary` support for fuzzing tests.
//! - `serde`: Serialization/deserialization support
//! - `rusqlite`: SQLite database integration
//! - `sea-orm`: SeaORM ORM integration  
//! - `prost`: Protocol Buffers support
//! - `redb`: `redb` integration
//!
//! # Examples
//!
//! ```rust
//! use caretta_id::CarettaId;
//! # fn main() -> Result<(), caretta_id::Error> {
//! // Generate random caretta-id
//! let caretta_id = CarettaId::random();
//! 
//! // e.g. `123abcd`
//! println!("'{}'", caretta_id);
//!
//! // Parse from string
//! let valid_id: CarettaId = "012atvw".parse()?;
//!
//! // When decoding from BASE32, ambiguous characters (1/l/I, 0/o, v/u) are treated as 1, 0 and v respectively, so they do not cause errors.
//! let also_valid_id: CarettaId = "ol2atuw".parse()?;
//! assert_eq!(valid_id, also_valid_id);
//!
//! // Convert to/from integer
//! let num: u64 = valid_id.into();
//! let id_from_int: CarettaId = num.try_into()?;
//! assert_eq!(valid_id, id_from_int);
//!
//! // Lossy conversion from oversized int is allowed.
//! let id_from_overflowed_int = CarettaId::from_u64_lossy(CarettaId::CAPACITY + num);
//! assert_eq!(valid_id, id_from_overflowed_int);
//!
//! # Ok(())
//! # }
//! ```
#![cfg_attr(not(feature = "std"), no_std)]
#![cfg_attr(docsrs, feature(doc_cfg))]

#[cfg(all(not(feature = "std"), not(test)))]
#[macro_use]
extern crate core as std;

/// Provides constants and private functions about encoding/decoding alphabet.
///
/// This module implements encoding and decoding character based on [Crockford's Base32](https://www.crockford.com/base32.html) with following exceptions:
///
/// - The letter `u` (`U`) is decoded to 27, same as `v`.
/// - Characters are separated by hyphens every three characters (triplet) during encoding.
///   During decoding, hyphens may be omitted or replaced with underscores.
pub mod alphabet;

mod double;
mod error;
mod macros;
mod quadruple;
mod single;
mod triple;

#[cfg(feature = "arbitrary")]
mod arbitrary;

#[cfg(feature = "rand")]
mod rand;

#[cfg(feature = "serde")]
mod serde;

#[cfg(feature = "prost")]
mod prost;

#[cfg(feature = "redb")]
mod redb;

#[cfg(feature = "rusqlite")]
mod rusqlite;

#[cfg(feature = "sea-orm")]
mod sea_orm;

/// Provides [`Triplet`](triplet::Triplet) and [`TripletError`](triplet::TripletError).
pub mod triplet;

use core::str::FromStr;
use std::fmt::Display;

pub use double::CarettaIdD;
pub use error::Error;
pub use quadruple::CarettaIdQ;
pub use single::CarettaIdS;
pub use triple::CarettaIdT;

use crate::alphabet::{BASE, char_to_u5, char_to_u8, u5_to_char_lossy};

/// Provides message types generated by prost-build.
#[cfg(feature = "prost")]
pub mod proto;

/// Alias of [`proto::CarettaIdS`]
#[cfg(feature = "prost")]
pub type CarettaIdSProto = proto::CarettaIdS;

/// Alias of [`proto::CarettaIdD`]
#[cfg(feature = "prost")]
pub type CarettaIdDProto = proto::CarettaIdD;

/// Alias of [`proto::CarettaIdT`]
#[cfg(feature = "prost")]
pub type CarettaIdTProto = proto::CarettaIdT;

/// Alias of [`proto::CarettaIdQ`]
#[cfg(feature = "prost")]
pub type CarettaIdQProto = proto::CarettaIdQ;

/// Alias of [`proto::CarettaId`]
#[cfg(feature = "prost")]
pub type CarettaIdProto = proto::CarettaId;

/// Caretta id struct
#[derive(Copy, Clone, Debug, Hash, PartialEq, Eq, PartialOrd, Ord)]
pub struct CarettaId(u64);

impl CarettaId {
    /// The size of the integer type in bits.
    /// 
    /// This is not equal actually stored size.
    pub const BITS: u32 = 35;

    /// The capacity value of the caretta id
    /// 
    pub const CAPACITY: u64 = (BASE as u64).pow(7);

    pub(crate) const CAPACITY_MINUS_ONE: u64 = Self::CAPACITY -1;

    pub(crate) const fn from_u64_unchecked(value: u64) -> Self {
        Self(value)
    }
    
    /// The smallest value that can be represented by [`CarettaId`].
    ///
    /// # Examples
    ///
    /// ```
    /// # use caretta_id::*;
    /// # fn main() -> Result<(), Error> {
    /// assert_eq!(CarettaId::NIL, "0000000".parse::<CarettaId>()?);
    /// assert_eq!(CarettaId::NIL, CarettaId::try_from(0)?);
    /// # Ok(())
    /// # }
    /// ```
    ///
    pub const NIL: Self = Self::from_u64_unchecked(0);

    /// The largest value that can be represented by [`CarettaId`].
    ///
    /// # Examples
    ///
    /// ```
    /// # use caretta_id::*;
    /// # fn main() -> Result<(), Error> {
    /// assert_eq!(CarettaId::MAX, "zzzzzzz".parse::<CarettaId>()?);
    /// assert_eq!(CarettaId::MAX, CarettaId::try_from(CarettaId::CAPACITY -1)?);
    /// # Ok(())
    /// # }
    /// ```
    ///
    pub const MAX: Self = Self::from_u64_unchecked(Self::CAPACITY_MINUS_ONE);

    /// Test if the [`CarettaId`] is nil.
    ///
    /// # Examples
    ///
    /// ```
    /// # use caretta_id::*;
    /// # fn main() -> Result<(), Error> {
    /// assert!("0000000".parse::<CarettaId>()?.is_nil());
    /// # Ok(())
    /// # }
    /// ```
    pub fn is_nil(&self) -> bool {
        self == &Self::NIL
    }

    /// Test if the [`CarettaId`] is max.
    ///
    /// # Examples
    ///
    /// ```
    /// # use caretta_id::*;
    /// # fn main() -> Result<(), Error> {
    /// assert!("zzzzzzz".parse::<CarettaId>()?.is_max());
    /// # Ok(())
    /// # }
    /// ```
    pub fn is_max(&self) -> bool {
        self == &Self::MAX
    }

    /// "Converts an unsigned integer to [`CarettaId`] by truncating bits that exceed the valid range.")]
    ///
    /// This is a lossy conversion that masks the input value to fit within the ID's bit limit.
    /// If you need to detect out-of-range values, use [`TryFrom`] instead.
    ///
    /// # Examples
    ///
    /// ```
    /// # use caretta_id::*;
    /// // Values within range are preserved
    /// let valid_int = 123;
    /// let id = CarettaId::from_u64_lossy(valid_int);
    /// assert_eq!(u64::from(id), valid_int);
    ///
    /// // values exceeding 35 bits are truncated (MSB(s) dropped
    /// let oversized_int = valid_int + CarettaId::CAPACITY;
    /// let overflowed_id = CarettaId::from_u64_lossy(oversized_int);
    /// assert_ne!(u64::from(overflowed_id), oversized_int);
    /// // Only lower 35 bits retained
    /// assert_eq!(u64::from(overflowed_id), valid_int)
    /// ```
    pub const fn from_u64_lossy(int: u64) -> Self {
        Self::from_u64_unchecked(int & Self::CAPACITY_MINUS_ONE)
    }

    pub const fn from_u64(value: u64) -> Result<Self, crate::Error> {
        if value < Self::CAPACITY {
            Ok(Self::from_u64_unchecked(value))
        } else {
            Err(Error::ValueOutOfRange(value))
        }
    }
    pub const fn as_u64(&self) -> &u64 {
        &self.0
    }
    pub const fn to_u64(self) -> u64 {
        self.0
    }
    fn from_chars(value: [char;7]) -> Result<Self, Error> {
        Ok(Self::from_u64_unchecked(u5s_to_u35_unchecked(chars_to_u5s(value)?)))
    }
    fn to_chars(self) -> [char;7] {
        [
            u5_to_char_lossy((self.0 >> 30) as u8) ,
            u5_to_char_lossy((self.0 >> 25) as u8) ,
            u5_to_char_lossy((self.0 >> 20) as u8) ,
            u5_to_char_lossy((self.0 >> 15) as u8) ,
            u5_to_char_lossy((self.0 >> 10) as u8) ,
            u5_to_char_lossy((self.0 >> 5) as u8) ,
            u5_to_char_lossy((self.0) as u8) ,
        ]  

    }
}

fn chars_to_u5s(value: [char;7]) -> Result<[u8;7], Error> {
    let mut result = [0;7];
    for i in 0 .. 7 {
        result[i] = char_to_u5(value[i]).ok_or(Error::InvalidCharacter { character: value[i], index: i })?;
    }
    Ok(result)
}

fn u5s_to_u35_unchecked(value: [u8;7]) -> u64 {
    ((value[0] as u64) << 30) |
    ((value[1] as u64) << 25) |
    ((value[2] as u64) << 20) |
    ((value[3] as u64) << 15) |
    ((value[4] as u64) << 10) |
    ((value[5] as u64) << 5) |
    (value[6] as u64)
}

impl AsRef<u64> for CarettaId {
    fn as_ref(&self) -> &u64 {
        self.as_u64()
    }
}

impl TryFrom<u64> for CarettaId {
    type Error = Error;
    #[doc = concat!("Attempts to convert a [`", stringify!($Uint), "`]  to [`", stringify!($SelfT), "`].")]
    ///
    /// Return error if the value is equal [`CAPACITY`](Self::CAPACITY) or more.
    /// If you don't need to detect out-of-range values, use [`from_uint_lossy`](Self::from_uint_lossy).
    ///
    /// # Examples
    ///
    /// ```
    /// # use caretta_id::*;
    /// assert!(CarettaId::try_from(CarettaId::CAPACITY - 1).is_ok());
    /// assert!(CarettaId::try_from(CarettaId::CAPACITY).is_err());
    /// ```
    ///
    fn try_from(value: u64) -> Result<Self, Self::Error> {
        Self::from_u64(value)
    }
}

impl From<CarettaId> for u64 {
    fn from(value: CarettaId) -> Self {
        value.0
    }
}

impl Display for CarettaId {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let chars = self.to_chars();
        write!(f, "{}{}{}{}{}{}{}", chars[0], chars[1], chars[2], chars[3], chars[4], chars[5], chars[6])
    }
}

impl FromStr for CarettaId {
    type Err = Error;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let len = s.len();
        if len == 7 {
            let mut chars = s.chars();
            Self::from_chars([
                chars.next().unwrap(),
                chars.next().unwrap(),
                chars.next().unwrap(),
                chars.next().unwrap(),
                chars.next().unwrap(),
                chars.next().unwrap(),
                chars.next().unwrap(),
            ])
        } else {
            Err(Error::InvalidLength(len))
        }
    }
}

