name: Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  format: 
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Install nightly rustfmt
        run: rustup component add --toolchain nightly rustfmt
      - name: Run rustfmt
        run: cargo +nightly fmt --check --all
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Run clippy
        run: cargo clippy --workspace
  test:
    name: Test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - macos-latest
          - windows-latest
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      run: cargo build --workspace --verbose
    - name: Run tests
      run: cargo test --workspace --verbose
